baseurl                  = "https://kim-s-h.github.io"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Seohyun Kim"
theme = "hugo-theme-sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "UA-185885638-2"                               # Tracking code, eg. "UA-111111111-1"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# enableGitInfo = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = "Seohyun Kim's personal website"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Seohyun Kim"
    # rss                = ""

#[[params.videoBackground.sources]]
#    source  = "/sample_video.mp4"
#    type    = "video/mp4"
#    poster  = "/background.png"
    
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "about"
    text = "seohyun kim"


[[params.mainMenu]]
    link = "projects"
    text = "projects"

#[[params.mainMenu]]
#    link = "papers"
#    text = "papers"


#[[params.mainMenu]]
#    link = "portfolio"
#    text = "portfolio"
    


[imaging]
    quality = 75
